apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    myapp: frontend
    tier: db

spec:
  containers:
    - name: frontend
      image: busybox
      command:
        - "sleep"
        - "50000"
      env:
        - name: user
          value: root
        - name: PASSWORD
          value: mysecret 
