apiVersion: v1
kind: Pod
metadata:
  name: multi-pod2

spec:
  volumes:
    - name: share
      emptyDir: {}

  containers:
    - name: multipod-2
      image: nginx
      volumeMounts:
        - name: html
        - mountPath: /pod-data/index.html
  resources:
  
