apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-nodeport
  labels:
    ingress: ingress-controller-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
     type: frontend
    