apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy1
  name: busy1
  namespace: myns
spec:
  containers:
  - image: busybox
    name: busy1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
