apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy2
  name: busy2
    run: busy3
  name: busy3
  namespace: myns
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello world
    image: busybox
    name: busy2
    resources: {}
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: busy3

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
