apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web01
  name: web01
spec:
  containers:
  - image: nginx
    name: web01
    volumeMounts:
    - name: home
      mountPath: /app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: home
    emptyDir: {}
status: {}
