apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: box
  name: box
  namespace: myns
spec:
  initContainers:
  - args:
    - /bin/sh
    - -c
    - wget -O /work-dir/index.html http://neverssl.com/online
    image: busybox
    name: box
    volumeMounts:
    - name: vol
    - mountPath: /work-dir
  containers:
  - image: nginx
    name: web01
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
    volumes:
    - name: vol
      emptyDir: {}
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

