apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  initContainers:
  - args:
    - /bin/sh
    - -c
    - wget -O /work/dir/index.html http://nerverssl.com/online
    image: busybox
    name: box
    volumeMounts:
    - name: vol
      mountPath: /work-dir
  containers:
  - image: nginx
    name: web
  volumes:
  - name: vol
    emptyDir: {}
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
