apiVersion: v1
kind: Pod
metadata:
  name: mi-pod
  labels:
    tier: pod
spec:
  containers:
    - image:  nginx
      name:  my-podgi
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: app-data-secret
  resources:
    cpu:
       

      