apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: data
spec:
  containers:
    - name: pod-3
      image: nginx
  containerports:
    - port: 80
  envFrom:
  configRef:
    - name: config-3  
  resources:
